{% set name = "apache-airflow-providers-common-io" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_common_io-{{ version }}.tar.gz
  sha256: 17a488220115f3acda47258cef762fb5fbf942b6a5930134b1da3e4ea775abf5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }},<4.dev0
    - apache-airflow >=2.9.0

test:
  imports:
    - airflow.providers.common.io
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://airflow.apache.org/
  summary: Provider package apache-airflow-providers-common-io for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/common/io/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-common-sql/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
